apiVersion: v1
kind: ReplicationController
metadata:
  name: solr-controller
  namespace: default
  labels:
    app: solr-controller
spec:
  replicas: 1
  selector:
    app: solr-app
  template:
    metadata:
      labels:
        app: solr-app
    spec:
      containers:
      - name: solr-container
        image: solr:6.6
        ports:
        - name: solr
          containerPort: 8983
          protocol: TCP
        env:
        - name: SOLR_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ZK_HOST
          value: zookeeper-service:2181
