apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-controller
  namespace: default
  labels:
    app: zookeeper-controller
spec:
  replicas: 1
  selector:
    app: zookeeper-app
  template:
    metadata:
      labels:
        app: zookeeper-app
    spec:
      containers:
      - name: zookeeper-container
        image: jplock/zookeeper:3.4.9
        ports:
        - name: zookeeper
          containerPort: 2181
          protocol: TCP
        env:
        - name: ZK_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
